version: "3"
services:
  api:
    container_name: latter-server
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    command: sh -c 'go mod tidy && air'
    env_file: ".env"